# Generated by Django 4.2.26 on 2025-12-07 17:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0002_movieproposal_imdb_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('action', models.CharField(choices=[('vote_add', 'Dodano głos'), ('vote_remove', 'Usunięto głos'), ('proposal_create', 'Nowa propozycja'), ('proposal_delete', 'Usunięto propozycję'), ('movie_mark_watched', 'Oznaczono jako obejrzane'), ('login', 'Logowanie')], max_length=50)),
                ('proposal_id', models.IntegerField(blank=True, null=True)),
                ('proposal_title', models.CharField(blank=True, max_length=255)),
                ('details', models.TextField(blank=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movie_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
