# Generated by Django 4.2.26 on 2025-12-07 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_logentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logentry',
            name='action',
            field=models.CharField(choices=[('vote_add', 'Dodano głos'), ('vote_remove', 'Usunięto głos'), ('proposal_create', 'Nowa propozycja'), ('proposal_delete', 'Usunięto propozycję'), ('movie_mark_watched', 'Oznaczono jako obejrzane'), ('login', 'Logowanie'), ('register', 'Rejestracja'), ('logout', 'Wylogowanie'), ('clear_logs', 'Wyczyszczono logi')], max_length=50),
        ),
    ]
