# Generated by Django 6.0 on 2026-01-19 13:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_logentry_action'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='logentry',
            name='action',
            field=models.CharField(choices=[('vote_add', 'Dodano głos'), ('vote_remove', 'Usunięto głos'), ('proposal_create', 'Nowa propozycja'), ('proposal_delete', 'Usunięto propozycję'), ('movie_mark_watched', 'Oznaczono jako obejrzane'), ('login', 'Logowanie'), ('register', 'Rejestracja'), ('logout', 'Wylogowanie'), ('clear_logs', 'Wyczyszczono logi'), ('password_changed', 'Zmieniono hasło')], max_length=50),
        ),
        migrations.CreateModel(
            name='MovieRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_title', models.CharField(max_length=255)),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('movie_title', 'user')},
            },
        ),
    ]
