# Generated by Django 6.0 on 2026-01-21 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_userproposallimit'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieproposal',
            name='cached_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movieproposal',
            name='cached_imdb_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
