# Generated by Django 6.0 on 2026-01-21 10:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_movieproposal_cached_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='media',
            options={'ordering': ['number']},
        ),
        migrations.AddField(
            model_name='media',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='media',
            name='poster_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='media',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='number',
            field=models.IntegerField(db_index=True, unique=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='skipped',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='media',
            name='title',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='media',
            name='votes',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='media',
            name='watched',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name='media',
            index=models.Index(fields=['watched', 'number'], name='home_media_watched_13f37e_idx'),
        ),
        migrations.AddIndex(
            model_name='media',
            index=models.Index(fields=['title', 'year'], name='home_media_title_c837fb_idx'),
        ),
    ]
